# Generated by Django 5.0.3 on 2024-05-01 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_alter_tag_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='username',
        ),
    ]
