# Generated by Django 5.0.3 on 2024-05-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_remove_tag_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
