# Generated by Django 5.0.3 on 2024-05-01 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0013_alter_tag_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='userId',
            new_name='user',
        ),
    ]
