# Generated by Django 5.0.3 on 2024-05-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0014_rename_userid_card_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='finished',
            field=models.BooleanField(blank=True, db_default=False, default=False, null=True),
        ),
    ]
