# Generated by Django 5.0.3 on 2024-05-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0015_card_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
