# Generated by Django 5.0.3 on 2024-05-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0017_alter_tag_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='tags',
            field=models.ManyToManyField(null=True, to='todoapp.tag'),
        ),
    ]
