# Generated by Django 5.0.3 on 2024-05-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0018_alter_card_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='tags',
            field=models.ManyToManyField(blank=True, to='todoapp.tag'),
        ),
    ]
